using Tyuiu.AlshinAF.Sprint3.Task5.V6.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #3 | Выполнил: Альшин А. Ф. | РППб-24-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #3                                                               *");
Console.WriteLine("* Тема:  Вложенные циклы                                                  *");
Console.WriteLine("* Задание #5                                                              *");
Console.WriteLine("* Вариант #6                                                              *");
Console.WriteLine("* Выполнил: Альшин Артур Фаритович | РППб-24-1                            *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* y = Сумма ряда от 1 до 3 суммы ряда от 1 до 10 1/cos(k) + 2             *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
int start1 = 1;
int start2 = 1;
int stop1 = 3;
int stop2 = 10;
Console.WriteLine("Старт шага первой суммы ряда = " + start1);
Console.WriteLine("Конец шага первой суммы ряда = " + stop1);
Console.WriteLine("Старт шага второй суммы ряда = " + start2);
Console.WriteLine("Конец шага второй суммы ряда = " + stop2);
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("Сумма ряда = " + ds.GetSumSumSeries(start1, start2, stop1, stop2));
Console.ReadKey();