using Tyuiu.AlshinAF.Sprint3.Task4.V25.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #3 | Выполнил: Альшин А. Ф. | РППб-24-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #3                                                               *");
Console.WriteLine("* Тема:  Использование операторов continue и break в циклах               *");
Console.WriteLine("* Задание #4                                                              *");
Console.WriteLine("* Вариант #25                                                             *");
Console.WriteLine("* Выполнил: Альшин Артур Фаритович | РППб-24-1                            *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* На отрезке, где x принимает значения от -5 до 5,вычислить значение      *");
Console.WriteLine("* функции y=x/(cos(x)-sin(x))                                             *");
Console.WriteLine("* При х = 0 пропустить значение. Полученные значения суммировать.         *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
int startValue = -5;
int stopValue = 5;
Console.WriteLine("Старт шага = " + startValue);
Console.WriteLine("Конец шага = " + stopValue);
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("Сумма ряда = " + ds.Calculate(startValue, stopValue));
Console.ReadKey();